name = "Cupper-dfd-x"
license = "MIT"
licenselink = "https://github.com/danielfdickinson/cupper-hugo-dfd-x/blob/main/LICENSE"
description = "An accessibility-friendly Hugo theme, forked from the cupper-hugo-theme project."
homepage = "https://github.com/danielfdickinson/cupper-hugo-dfd-x"
tags = ["accessible", "blog", "documentation", "dark"]
features = ["accessible", "blog", "documentation", "dark"]
min_version = "0.87.0"

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.danielfdickinson.ca/about"

[original]
  name = "Zachary Betz"
  homepage = "https://zwbetz.com/"
  repo = "https://github.com/zwbetz-gh/cupper-hugo-theme"
